<!DOCTYPE html>
<html lang="zh-CN">
  <head>
   <title>湖南芒谷食品有限公司</title>
  <meta http-equiv="X-UA-Compatible" content="IE=Edge">
  <meta name="description"
          content="湖南芒谷食品有限公司,养生,中医养生,养生方法,养生产品,湖南芒谷食品有限公司,芒谷食品,芒谷,保养,食品,药膳,,药膳养生"/>
    <meta name="keywords"
          content="养生,中医养生,养生方法,养生产品,湖南芒谷食品有限公司,芒谷食品,芒谷,保养,食品,药膳,,药膳养生"/>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="./bootstrap/css/bootstrap.css">
    <link rel="stylesheet" href="./tether/css/tether.css">
    <link rel="stylesheet" href="./css/common.css">
    <link rel="stylesheet" href="./css/index.css">
    <script src="/js/jquery-1.11.0.min.js"></script>
    <script src="/bootstrap/js/bootstrap.js"></script>
    <script src="/js/hammer/hammer.min.js"></script>
    <script src="/js/hammer/jquery.hammer.js"></script>
    <style>
      .container{
        max-width: 860px;
      }
      .copy{
        margin-top: 0px;
      }
      img {
        margin:0px;
        padding:0px;
        width:100%;
      }
      .div_box {
        margin-left:12px;
      }
      .row {
        margin-bottom:8px;
      }
      .none{
        padding: 0px;margin: 0px
      }
    </style>

  </head>
  <body>
  <div class="container">
    <div class="row" >
        <div class="col-md-4 hidden-xs hidden-sm">
        </div>
        <div class="col-md-4 col-xs-12 col-sm-12">
          <div class="div_box">
            <img class="center-block" src="/images/index/logo.gif" />
          </div>
        </div>
        <div class="col-md-4 hidden-xs hidden-sm">
        </div>
    </div>
    <div class="row" >
      <div class="col-xs-12 col-sm-12 col-md-4">
        <div class="row">
          <div class="div_box">
              <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="3000">
                <!-- 轮播（Carousel）指标 -->
                <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                    <li data-target="#myCarousel" data-slide-to="2"></li>
                </ol>
                <!-- 轮播（Carousel）项目 -->
                <div class="carousel-inner">
                    <div class="item active">
                      <img src="/images/index/index_01.png" alt="First slide">
                    </div>
                    <div class="item">
                      <img src="/images/index/index_01.png" alt="Second slide">
                    </div>
                    <div class="item">
                      <img src="/images/index/index_01.png" alt="Third slide">
                    </div>
                </div>
                <!-- 轮播（Carousel）导航
                <a class="carousel-control left" href="#myCarousel"
                    data-slide="prev"></a>
                <a class="carousel-control right" href="#myCarousel"
                    data-slide="next"></a>-->
              </div>

          </div>
        </div>
        <div class="row">
          <div class="col-xs-6 col-sm-6 none">
            <div class="div_box">
              <figure class="effect-bubba">
                <a href="/home/article">
                  <img src="/images/index/index_10.png" />
                  <figcaption>
                    <h4>中医养生</h4>
                  </figcaption>
                </a>
              </figure>
            </div>
          </div>
          <div class="col-xs-6 col-sm-6 none">
            <div class="div_box">
              <figure class="effect-bubba">
                <a href="/home/article">
                  <img src="/images/index/index_09.png" />
                  <figcaption>
                    <h4>中医养生</h4>
                  </figcaption>
                </a>
              </figure>
            </div>
          </div>

        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-4">
        <div class="row">
          <div class="div_box">
            <figure class="effect-bubba">
              <a href="/home/survey">
                <img src="/images/index/index_02.png" />
                <figcaption>
                  <h4>体质测试</h4>
                </figcaption>
              </a>
            </figure>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-6 col-sm-6 none">
            <div  class="div_box">
              <figure class="effect-bubba">
                <a href="/home/article">
                  <img src="/images/index/index_07.png" />
                  <figcaption>
                    <h4>养生必读</h4>
                  </figcaption>
                </a>
              </figure>
            </div>
          </div>
          <div class="col-xs-6 col-sm-6 none">
            <div  class="div_box">
              <figure class="effect-bubba">
                <a href="/home/article">
                  <img src="/images/index/index_08.png" />
                  <figcaption>
                    <h4>中医养生</h4>
                  </figcaption>
                </a>
              </figure>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="div_box">
            <figure class="effect-bubba">
              <a href="/home/know">
                <img src="/images/index/index_05.png" />
                <figcaption>
                  <h4>辨清体质</h4>
                </figcaption>
              </a>
            </figure>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-4">
        <div class="row">
          <div  class="div_box">
            <figure class="effect-bubba">
              <a href="/home/product">
                <img src="/images/index/index_03.png" />
                <figcaption>
                  <h4>养生调理产品</h4>
                </figcaption>
              </a>
            </figure>

          </div>
        </div>
        <div class="row">
          <div class="div_box">
            <figure class="effect-bubba">
              <a href="/home/soma">
                <img src="/images/index/index_04.png" />
                <figcaption>
                  <h4>体质与健康</h4>
                </figcaption>
              </a>
            </figure>

          </div>
        </div>
        <div class="row">
          <div class="div_box">
            <figure class="effect-bubba">
              <a href="/home/about">
                <img src="/images/index/index_06.png" />
                <figcaption>
                  <h4>关于我们</h4>
                </figcaption>
              </a>
            </figure>

          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="copy" style="border-top: none">
    <p>中医养生 湖南芒谷食品有限公司
    </p>
   <!-- <p>网站备案/许可证号:</p> -->
  </div>
  <script>
    $('#myCarousel').hammer().on('swipeleft', function(){
      $(this).carousel('next');
    });
    $('#myCarousel').hammer().on('swiperight', function(){
      $(this).carousel('prev');
    });
  </script>
  </body>
</html>
